### ISSUE TITLE
Failed to fetch Overseerr requests

### ISSUE THREAD

**Issue by JonnySiHI** [mplewis/coaxist#20]
**Describe the bug**

Managed to get it setup but i keep getting the below Overseerr error
[16:43:37.634] ERROR (583): failed to fetch Overseerr requests

    errors: [

      {

        "status": 403,

        "statusText": "Forbidden",

        "text": "{\"status\":403,\"error\":\"You do not have permission to access this endpoint\"}"

      }

    ]
![image](https://github.com/mplewis/coaxist/assets/13147183/3e61fa3f-3e87-4b97-b838-41c639698bdf)

**What do you see in the logs?**
![image](https://github.com/mplewis/coaxist/assets/13147183/5204800a-e282-4d56-975b-450813b3254f)

**Comment by mplewis** [comment]
Hi @JonnySiHI, thanks for trying this software out. On startup, Connector tries to get the Overseerr API key from the Overseerr config file, and Overseerr creates that file on startup – so let's figure out what is going on here.

Were you able to sign into both Plex and Overseerr with your Plex account successfully? This is [step 3](https://github.com/mplewis/coaxist/blob/main/docs/quick-start.md#3-sign-in) of the Quick Start guide. Plex is at http://localhost:32400/web, and Overseerr is at http://localhost:5055/.

Once you've signed into both apps, can you try restarting the container and let me know if you still have this issue?

**Comment by mplewis** [comment]
I've shipped a version of the container with better debug logging. Can you try running the latest version and set env var `LOG_LEVEL=debug` as well, to help verify that your Overseerr API key in Connector matches that in `/config/overseerr/settings.json`?

**Comment by JonnySiHI** [comment]
Thanks :), fantastic program by the way. It seems to be working now since i updated to your latest build. However all the media files are getting mixed up the films and series are being blended in each others libraries, though i think this is due to only having the directory of /media on both Films and TV Shows. Also i have to run the container in privileged mode, otherwise the mount fails. 

Any chance of a Jellyfin build with Jellyseerr as the requester :)

**Comment by mplewis** [comment]
Yes, I have the same issue with the libraries. I'm working on a couple of approaches to separating TV from movies out on disk.

I also have the mount working in privileged mode and I don't know of a good alternative. If anyone finds a good way to make the mount work, let me know and I'd be happy to try it out and add it to the readme.

I don't have the resources to work on a Jellyfin/Jellyseerr build at this time, but I welcome a fork if someone wants to put it together, and would be happy to work together on this.

**Comment by JonnySiHI** [comment]
> Yes, I have the same issue with the libraries. I'm working on a couple of approaches to separating TV from movies out on disk.
> 
> I also have the mount working in privileged mode and I don't know of a good alternative. If anyone finds a good way to make the mount work, let me know and I'd be happy to try it out and add it to the readme.
> 
> I don't have the resources to work on a Jellyfin/Jellyseerr build at this time, but I welcome a fork if someone wants to put it together, and would be happy to work together on this.


pdrcrd https://github.com/I-am-PUID-0/pdrcrd seems to do a good job at mounting without the need of privilage mode, i think this is because of how the volume is mapped.
